### ISSUE TITLE
Breaks w/Cypress 7.1.0

### ISSUE THREAD

**Issue by jimpriest** [LironEr/cypress-mochawesome-reporter#27]
**Describe the bug**
After upgraded to Cypress 7.1.0 I get an error (see below)
Rolling back Cypress to 7.0.1 things work again.

**Expected behavior**
Should work as before.

**Environment**
`cypress-mochawesome-reporter` version: `2.0.1`
`cypress` version: `7.1.0`

**Additional context**

```
jpriest@home : ~/www/cypress (master *=)$ npx cypress run --headless --spec "cypress/integration/foo/bar.spec.js"                                                                                                       
The function exported by the plugins file threw an error.

We invoked the function exported by `/Users/jpriest/www/cypress/cypress/plugins/index.js`, but it threw an error.

 Error: Cannot find module 'cypress-mochawesome-reporter/lib'
Require stack:
- /Users/jpriest/www/cypress/cypress/plugins/index.js
- /Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (/Users/jpriest/www/cypress/cypress/plugins/index.js:21:2)
    at /Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:90:12
    at tryCatcher (/Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:87:7)
    at EventEmitter.<anonymous> (/Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:198:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/Users/jpriest/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by LironEr** [comment]
I just updated all the examples to use cypress `7.1.0` and everything works ok.

Please try to install the reporter again, validate that the reporter actually exists in node_modules.

If it doesn't work please provide steps to reproduce or reproduction repository

**Comment by jimpriest** [comment]
Hmm thanks for confirmation that it works. Let me uninstall and try again.

**Comment by LironEr** [comment]
@jimpriest any update?

If it still doesn't work please provide steps to reproduce or reproduction repository

**Comment by jimpriest** [comment]
This IS working properly.  Someone had installed some other mocha plugins before which seems to have caused the issue.  I uninstalled everything,  updated Cypress and reinstalled this plugin and it works.   Thanks!!
